title: Bitrise DevCenter
email: edusimonpicon@gmail.com
description: Green and In Backend
baseurl: '/'
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-menus
  - jekyll-redirect-from
  - localization
  - jekyll-seo-tag
collections:
  docs:
    output: true
    permalink: "/:path/"
