title: Green And In Backend
email: edusimonpicon@gmail.com
description: Green and In Backend
markdown: kramdown
remote_theme: pmarsceill/just-the-_docs
logo: "/assets/icon.jpg"
# Define Jekyll collections
collections:
  # Define a collection named "_docs", its documents reside in the "_docs" directory
  docs:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  # Define which collections are used in just-the-docs
  collections:
    # Reference the "docs" collection
    docs:
      # Give the collection a name
      name: Documentation
      # Exclude the collection from the navigation
      # Supports true or false (default)
      nav_exclude: false
      # Exclude the collection from the search
      # Supports true or false (default)
      search_exclude: false
